import type { IDeviceSelectOption } from "../types/device";

export enum DeviceType {
  Refrigerator = 1,
  VacuumCleaner,
  AirConditioner,
  TV,
  Phone,
  PC,
  Printer,
  MFU,
  Iron,
  Hairdryer,
  Fan,
  Heater,
  Humidifier,
  Lighting,
  Microwave,
  ElectricKettle,
  Dishwasher,
  Mixer,
  Juicer,
  ElectricOven,
}

export const DEVICE_SELECT_OPTONS: IDeviceSelectOption[] = [
  { type: DeviceType.Refrigerator, label: "Refrigerator" },
  { type: DeviceType.VacuumCleaner, label: "Vacuum Cleaner" },
  { type: DeviceType.AirConditioner, label: "Air Conditioner" },
  { type: DeviceType.TV, label: "TV" },
  { type: DeviceType.Phone, label: "Phone" },
  { type: DeviceType.PC, label: "PC" },
  { type: DeviceType.Printer, label: "Printer" },
  { type: DeviceType.MFU, label: "MFU" },
  { type: DeviceType.Iron, label: "Iron" },
  { type: DeviceType.Hairdryer, label: "Hairdryer" },
  { type: DeviceType.Fan, label: "Fan" },
  { type: DeviceType.Heater, label: "Heater" },
  { type: DeviceType.Humidifier, label: "Humidifier" },
  { type: DeviceType.Lighting, label: "Lighting" },
  { type: DeviceType.Microwave, label: "Microwave" },
  { type: DeviceType.ElectricKettle, label: "Electric Kettle" },
  { type: DeviceType.Dishwasher, label: "Dishwasher" },
  { type: DeviceType.Mixer, label: "Mixer" },
  { type: DeviceType.Juicer, label: "Juicer" },
  { type: DeviceType.ElectricOven, label: "Electric Oven" },
];
