import type { IDeviceSelectOption } from "../types/device";
import {
  BulbOutlined,
  PhoneOutlined,
  PrinterOutlined,
  DesktopOutlined,
  FireOutlined,
  SmileOutlined,
  ReloadOutlined,
  CloudOutlined,
  CoffeeOutlined,
  DropboxOutlined,
  ThunderboltOutlined,
  AppstoreOutlined,
  UsbFilled,
  ToolOutlined,
  DatabaseOutlined,
} from "@ant-design/icons";

export enum DeviceType {
  Refrigerator = 1,
  VacuumCleaner,
  AirConditioner,
  TV,
  Phone,
  PC,
  Printer,
  MFU,
  Hairdryer,
  Heater,
  Humidifier,
  Lighting,
  Microwave,
  ElectricKettle,
  Dishwasher,
  Mixer,
  ElectricOven,
  Other,
}

export const DEVICE_SELECT_OPTONS: IDeviceSelectOption[] = [
  {
    type: DeviceType.Refrigerator,
    label: "Refrigerator",
    icon: <DropboxOutlined />,
  },
  {
    type: DeviceType.VacuumCleaner,
    label: "Vacuum Cleaner",
    icon: <ToolOutlined />,
  },
  {
    type: DeviceType.AirConditioner,
    label: "Air Conditioner",
    icon: <CloudOutlined />,
  },
  { type: DeviceType.TV, label: "TV", icon: <DesktopOutlined /> },
  { type: DeviceType.Phone, label: "Phone", icon: <PhoneOutlined /> },
  { type: DeviceType.PC, label: "PC", icon: <DesktopOutlined /> },
  { type: DeviceType.Printer, label: "Printer", icon: <PrinterOutlined /> },
  { type: DeviceType.MFU, label: "MFU", icon: <PrinterOutlined /> },
  { type: DeviceType.Hairdryer, label: "Hairdryer", icon: <SmileOutlined /> },
  { type: DeviceType.Heater, label: "Heater", icon: <FireOutlined /> },
  { type: DeviceType.Humidifier, label: "Humidifier", icon: <CloudOutlined /> },
  { type: DeviceType.Lighting, label: "Lighting", icon: <BulbOutlined /> },
  { type: DeviceType.Microwave, label: "Microwave", icon: <FireOutlined /> },
  {
    type: DeviceType.ElectricKettle,
    label: "Electric Kettle",
    icon: <CoffeeOutlined />,
  },
  {
    type: DeviceType.Dishwasher,
    label: "Dishwasher",
    icon: <DropboxOutlined />,
  },
  { type: DeviceType.Mixer, label: "Mixer", icon: <ThunderboltOutlined /> },
  {
    type: DeviceType.ElectricOven,
    label: "Electric Oven",
    icon: <FireOutlined />,
  },
  { type: DeviceType.Other, label: "Other", icon: <AppstoreOutlined /> },
];
